#!/bin/sh

COLOR='\033[0;35m'
NC='\033[0m'

sudo apt install -y curl
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
curl -fsSL get.docker.com -o /tmp/get-docker.sh
sudo sh /tmp/get-docker.sh
sudo apt install -y git nodejs python-pip

echo -e "${COLOR}-------| Preparation complete. Now install it |-------${NC}"
