# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Anthology')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('checked_level', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startv', models.IntegerField(default=0)),
                ('endv', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
            options={
                'ordering': ['startv'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('anthology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Anthology')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mode')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_source', to='api.Language')),
            ],
            options={
                'ordering': ['language', 'version', 'book'],
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('markers', models.TextField(blank=True)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chunk')),
            ],
            options={
                'ordering': ['chunk'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Version'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('version', 'anthology', 'language', 'mode', 'book')]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('anthology', 'slug')]),
        ),
    ]
