# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='anthology',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Anthology'),
        ),
        migrations.AlterField(
            model_name='project',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Version'),
        ),
    ]
