# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Take',
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='file',
            new_name='take',
        ),
    ]
