# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170703_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='code',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='code',
            new_name='slug',
        ),
    ]
