# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171030_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
    ]
