# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170706_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
