# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='is_export',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='take',
            name='source',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
