# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170707_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='source',
        ),
        migrations.AddField(
            model_name='take',
            name='is_source',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
