# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170710_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='is_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='take',
            name='is_source',
            field=models.BooleanField(default=False),
        ),
    ]
