# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170710_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='source_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_source', to='api.Language'),
        ),
    ]
