# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_take_source_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('checked_level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startv', models.IntegerField(default=0)),
                ('endv', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
            options={
                'ordering': ['startv'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=3)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('anthology', models.CharField(blank=True, max_length=2)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Book')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('source_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_source', to='api.Language')),
            ],
            options={
                'ordering': ['language', 'version', 'book'],
            },
        ),
        migrations.AlterModelOptions(
            name='take',
            options={'ordering': ['chunk']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='file',
            new_name='take',
        ),
        migrations.RemoveField(
            model_name='take',
            name='anthology',
        ),
        migrations.RemoveField(
            model_name='take',
            name='book',
        ),
        migrations.RemoveField(
            model_name='take',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='take',
            name='checked_level',
        ),
        migrations.RemoveField(
            model_name='take',
            name='endv',
        ),
        migrations.RemoveField(
            model_name='take',
            name='language',
        ),
        migrations.RemoveField(
            model_name='take',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='take',
            name='source_language',
        ),
        migrations.RemoveField(
            model_name='take',
            name='startv',
        ),
        migrations.RemoveField(
            model_name='take',
            name='version',
        ),
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chunk'),
        ),
        migrations.AddField(
            model_name='take',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chunk'),
        ),
    ]
