# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0010_auto_20170719_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='chunk',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='take',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
