# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170719_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_modified']},
        ),
    ]
