# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170720_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='is_export',
        ),
        migrations.RemoveField(
            model_name='take',
            name='is_source',
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_source',
            field=models.BooleanField(default=False),
        ),
    ]
