# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170720_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='take',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
