# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170724_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='take',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
